# ha-tunnel-addon/config.yaml
name: "Secure Tunnel"
version: "1.0.1"
slug: "hap_secure_tunnel"
description: "Connects your Home Assistant to the Secure Tunneling Service."
url: "https://github.com/webfork/hap-addon"
arch:
  - aarch64
  - amd64
  - armv7
init: false
boot: "auto"
hassio_role: "homeassistant"
host_network: true
privileged:
  - NET_ADMIN
options:
  api_key: ""
schema:
  api_key: "password"